//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jonesie.Web.Module.Blog.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Jonesie.Web.Module.Blog.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete 
        ///  BlogPost 
        ///where
        ///    id = @Id.
        /// </summary>
        internal static string BlogPost_Delete {
            get {
                return ResourceManager.GetString("BlogPost_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select	
        ///  Id, Title, Author, Email, Body, Posted
        ///from
        ///  BlogPost 
        ///where
        ///    id = @Id.
        /// </summary>
        internal static string BlogPost_Get {
            get {
                return ResourceManager.GetString("BlogPost_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if exists (select 1 from BlogPost where Id = @Id)
        ///begin
        ///  update
        ///    BlogPost
        ///  set
        ///    Title = @Title, Author = @Author, Email = @Eail, Body = @Body, Posted = @Posted
        ///  where
        ///    Id = @Id
        ///
        ///end
        ///else
        ///begin
        ///  insert BlogPost (Title, Author, Email, Body, Posted)
        ///  values (@Id, @Title, @Author, @Email, @Body, GETUTCDATE())
        ///end.
        /// </summary>
        internal static string BlogPost_Update {
            get {
                return ResourceManager.GetString("BlogPost_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select	
        ///  Id, Title, Author, Email, Body, Posted
        ///from
        ///  Blog_Post 
        ///where
        ///    1 = 1 {0}
        ///order by
        ///  {1}
        ///offset @FirstItem - 1 rows
        ///fetch next @PageSize rows only;
        ///
        ///select
        ///  count(*) total_rows
        ///from
        ///  Blog_Post
        ///where 
        ///  1=1 {0};
        ///.
        /// </summary>
        internal static string BlogPosts_Get {
            get {
                return ResourceManager.GetString("BlogPosts_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[Blog_Post]
        ///(
        ///  [Id] INT IDENTITY NOT NULL PRIMARY KEY,
        ///  Title nvarchar(250) NOT NULL,
        ///  Author nvarchar(120) NOT NULL,
        ///  Email nvarchar(120) NOT NULL,
        ///  Posted datetimeoffset NOT NULL,
        ///  Body nvarchar(MAX) NOT NULL
        ///)
        ///
        ///GO
        ///
        ///CREATE TABLE [dbo].[Blog_Comment]
        ///(
        ///  [Id] INT IDENTITY NOT NULL PRIMARY KEY,
        ///  PostId INT NOT NULL,
        ///  Author nvarchar(120) NOT NULL,
        ///  Email nvarchar(120) NOT NULL,
        ///  Posted datetimeoffset NOT NULL,
        ///  Body nvarchar(MAX) NOT NULL,
        ///  CONSTRAINT [fk_B [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Schema_Blog_1 {
            get {
                return ResourceManager.GetString("Schema_Blog_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[Blog_Comment]
        ///(
        ///  [Id] INT IDENTITY NOT NULL PRIMARY KEY,
        ///  PostId INT NOT NULL,
        ///  Author nvarchar(120) NOT NULL,
        ///  Email nvarchar(120) NOT NULL,
        ///  Posted datetimeoffset NOT NULL,
        ///  Body nvarchar(MAX) NOT NULL,
        ///  CONSTRAINT [fk_BlogComment_BlogPost] FOREIGN KEY (PostId) REFERENCES [dbo].[Blog_Post] (Id)
        ///)
        ///
        ///
        ///.
        /// </summary>
        internal static string Table_BlogComment {
            get {
                return ResourceManager.GetString("Table_BlogComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[Blog_Post]
        ///(
        ///  [Id] INT IDENTITY NOT NULL PRIMARY KEY,
        ///  Title nvarchar(250) NOT NULL,
        ///  Author nvarchar(120) NOT NULL,
        ///  Email nvarchar(120) NOT NULL,
        ///  Posted datetimeoffset NOT NULL,
        ///  Body nvarchar(MAX) NOT NULL
        ///)
        ///.
        /// </summary>
        internal static string Table_BlogPost {
            get {
                return ResourceManager.GetString("Table_BlogPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[Blog_PostTag]
        ///(
        ///  PostId INT NOT NULL,
        ///  TagId INT NOT NULL
        ///  PRIMARY KEY CLUSTERED (PostId ASC, TagId ASC),
        ///  CONSTRAINT [fk_BlogPostTag_BlogPost] FOREIGN KEY (PostId) REFERENCES [dbo].[Blog_Post] (Id) ON DELETE CASCADE,
        ///  CONSTRAINT [fk_BlogPostTag_BlogTag] FOREIGN KEY (TagId) REFERENCES [dbo].[Blog_Tag] (Id) ON DELETE CASCADE
        ///)
        ///.
        /// </summary>
        internal static string Table_BlogPostTag {
            get {
                return ResourceManager.GetString("Table_BlogPostTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[Blog_Tag]
        ///(
        ///  [Id] INT IDENTITY NOT NULL PRIMARY KEY,
        ///  Name nvarchar(150) NOT NULL
        ///)
        ///.
        /// </summary>
        internal static string Table_BlogTag {
            get {
                return ResourceManager.GetString("Table_BlogTag", resourceCulture);
            }
        }
    }
}
